config/routes.rb
Rails.application.routes.draw do
  root "landing_pages#index"

  get "/get_synonyms/:word" => "posts#get_synonyms"

  namespace :admin do
    resources :prompts
  end

  resources :users, path: "writers"
  get "/welcome" => "users#welcome"
  get "/profile" => "users#show"
  get "/writers/:id/stats" => "users#stats", as: :stats

  resources :posts, except: [:edit]
  get "/write" => "posts#edit", as: :write
  post "/publish/:post_id" => "posts#publish", as: :publish
  post "/unpublish/:post_id" => "posts#unpublish", as: :unpublish
  get "/refresh_random_prompt" => "posts#refresh_random_prompt"

  resources :comments, only: [:create]

  resources :archive, only: [:index]
  get "/download" => "archive#download", as: :download

  resources :landing_pages

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  post "/logout" => "sessions#destroy", as: :logout

  resources :password_resets
  resources :subscriptions
  delete "/destroy_subscription" => "subscriptions#destroy",
    as: :destroy_subscription
  resources :refunds, only: [:create]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :skip_password_validation

  has_many :posts do
    def today
      (where "created_at >= ?", Time.zone.now.beginning_of_day).first
    end
  end

  has_many :password_resets
  has_many :refunds

  validates :username, :email, uniqueness: true, presence: true
  validates :email, format: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i
  validates :password, length: { minimum: 8 }, unless: :skip_password_validation

  scope :subscribers, -> { where(unsubscribe: false) }

  has_many :achievements
  has_secure_password
  has_streak

  def days_left_in_trial
    if days_since_registration >= 7
      0
    else
      7 - days_since_registration
    end
  end

  def update_longest_streak
    current_streak = streak(:posts)
    if current_streak >= longest_streak
      update_attribute(:longest_streak, current_streak)
    end
  end

  def days_since_registration
    (Date.today - created_at.to_date).to_i
  end

  def weeks_since_registration
    days_since_registration / 7
  end

  def week_day_since_registration
    days_since_registration % 7
  end

  def is_public_profile?
    ! posts.published.empty?
  end

  def total_words
    posts.sum(:word_count)
  end

  def eligible_for_refund?
    return false if refunds.any? {|refund| refund.created_at > 1.month.ago }

    (streak(:posts) || 0) >= 30
  end
end

app/controllers/users_controller.rb
class UsersController < AuthenticatedController
  skip_before_action :require_user, only: [:new, :create]
  skip_before_action :require_subscriber, only: [:new, :create, :edit]

  def index
    @profile = Profile.new(current_user, view_context)
    @users = User.all.order("longest_streak DESC")
      .paginate(page: params[:page], per_page: 50)
  end

  def new
    @user = User.new
  end

  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
    @profile = Profile.new(@user, view_context)
  end

  def stats
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
    @profile = Profile.new(@user, view_context)
  end

  def edit
    @profile = Profile.new(current_user, view_context)
  end

  def update
    @user = current_user
    @user.skip_password_validation = true

    if @user.update(settings_params)
      redirect_to user_path(@user)
    else
      @profile = Profile.new(@user, view_context)
      render :edit
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      WelcomeEmailJob.perform_later(@user, Prompt.today.content)
      set_current_user(@user.id)
      redirect_to welcome_path
    else
      render :new
    end
  end

  def welcome
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :unsubscribe)
  end

  def settings_params
    params.require(:user).permit(:email, :unsubscribe)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def add_errors_of(errors, field)
    if errors.include?(field)
      errors.full_messages_for(field).each do |msg|
        concat(content_tag(:div, msg, class: 'error-msg'))
      end
    end
  end
end

app/views/users/edit.html.haml
= render 'layouts/side_bar'

.col-sm-3.col-sm-offset-3
  = link_to "&#10094; back to my profile".html_safe, profile_path, class: "back"

.col-sm-9.col-sm-offset-3.settings-section
  = flash_message
  %h4 Settings
  = form_for @profile.user, html: { class: "settings-form" } do |f|
    .form-field
      = f.label :email
      = f.text_field :email
      - add_errors_of(@profile.user.errors, :email )
    .form-field
      = f.label :unsubscribe, "Unsubscribe from daily emails"
      = f.check_box :unsubscribe
    %br
    = f.submit "Update settings", class: "button"

  - if feature_active?(:payments)
    - unless @profile.user.paid
      %h4
        Trial:
        = @profile.user.days_left_in_trial
        days remaining.

      = form_tag subscriptions_path do
        %script.stripe-button{ |
          "data-amount" => ENV["BASIC_PLAN_AMOUNT_CENTS"], |
          "data-description" => "Monthly subscription", |
          "data-key" => ENV["STRIPE_PUBLISHABLE_KEY"], |
          "src" => "https://checkout.stripe.com/checkout.js"}
    - else
      %h4 Cancel subscription
      = link_to "Cancel", destroy_subscription_path, class: "button--danger", method: :delete,
        data: { confirm: "Are you sure you want to cancel your subscription? You won't be able to use Verba if you choose to cancel." }

    %p.content--small.breathe.refund-explanation If you write for 30 days in a row, you'll have the option to be refunded your monthly subscription fee.
    = @profile.refund_button

app/views/users/index.html.haml
= render 'layouts/side_bar'


.col-sm-3.col-sm-offset-3
  = link_to "&#10094; back to my profile".html_safe, profile_path, class: "back"

.col-sm-9.col-sm-offset-3.stats
  %h1.heading Writers
  %table.writers-table
    %tr
      %th
        Username
      %th
        Words written
      %th
        Longest streak
    - @users.each do |user|
      %tr
        %td
          = link_to user.username, user_path(user), class: "link"
        %td
          = user.total_words
        %td
          = user.longest_streak


- unless @users.empty?
  = will_paginate @users

app/views/users/new.html.haml
.row
  .col-sm-12
    .verba-brand
      = image_tag("https://d1015h9unskp4y.cloudfront.net/attachments/bae8bafd-4081-4b2b-b6f4-c9d4c367ded8/verba.png", class: "verba-logo")

.row
  .col-sm-12
    = form_for(@user, html: {class: "form signup" }) do |f|

      .form-group
        .row
          .col-md-6.col-sm-12
            .form-field
              = f.text_field :username, placeholder: "username"
              - add_errors_of(@user.errors, :username )
          .col-md-6.col-sm-12
            .form-field
              = f.text_field :email, placeholder: "email"
              - add_errors_of(@user.errors, :email )
      .form-group
        .row
          .col-md-6.col-sm-12
            .form-field
              = f.password_field :password, placeholder: "password"
              - add_errors_of(@user.errors, :password )
          .col-md-6.col-sm-12
            .form-field
              = f.password_field :password_confirmation, placeholder: "password confirmation"
              - add_errors_of(@user.errors, :password_confirmation )
      .row
        .col-sm-12
          .submit-form
            = submit_tag "Register"

          .login-or-register
            = link_to "Log in", login_path, class: 'link'

app/views/users/show.html.haml
= render 'layouts/side_bar'

.col-sm-9.user-posts
  = flash_message
  = link_to "Keep writing", new_post_path, class: "keep-writing pull-right"
  - unless @profile.current_users_profile?
    = link_to "&#10094; back to my profile".html_safe, profile_path, class: "back-main"
  %h1.title
    Posts
  - if @profile.posts.present?
    - @profile.posts.each do |post|
      = render partial: "posts/post", locals: { post: post }

    = will_paginate @profile.posts

  - else
    = render "posts/post_blank_state"

app/views/users/stats.html.haml
= render 'layouts/side_bar'

.col-sm-3.col-sm-offset-3
  = link_to "&#10094; back to my profile".html_safe, profile_path, class: "back"

.col-sm-9.col-sm-offset-3.stats
  %h4 This week
  .days-visual
    - @profile.days_of_the_week.each do |day|
      - post_today = @profile.user.posts.on_date(day)

      - if post_today.first.present?
        %div{class: "day-cell"}
          %div.word-count-for-day.hidden
            = post_today.first.date(without_year: true)
            %br
            = post_today.first.word_count.to_s + " words"
      - else
        %span{class: "empty-day-cell"}

  %h4 Other stats
  .other-stats
    .other-stat
      %p Longest streak
      = @profile.user.longest_streak
    .other-stat
      %p Total words written
      = @profile.user.total_words

  %h4 Achievements
  .achievements-stats-page
    - @profile.user.achievements.each do |achievement|
      .achievement
        %span{class: "#{achievement.tier}-badge-small"}
        = achievement.name
      %p.achievement--description= achievement.description

app/views/users/welcome.html.haml
%article.welcome
  = image_tag "https://d1015h9unskp4y.cloudfront.net/attachments/bae8bafd-4081-4b2b-b6f4-c9d4c367ded8/verba.png", width: "200px"
  %p.col-md-6
    Welcome
    %span= current_user.username + "!"
  %p.col-md-6
    You're here because you want to become a better writer and communicator. Verba is here to help.

  %p.col-md-6
    Here's how Verba works:

  %ul.welcome-list.col-md-6
    %li.welcome-list__item
      We send you a writing prompt every day. Feel free to write about whatever you want, the prompt is only there to help you if you can't think of anything to write about.
    %li.welcome-list__item
      We'll keep track of a few key stats including word count and streaks of consecutive days that you write. Consistency is the name of the game.
    %li.welcome-list__item
      If you need some additional motivation, you can earn badges for reaching certain milestones, like keeping up a writing streak of five days.
    %li.welcome-list__item
      Your posts are private by default, but you may choose to publish them to the Verba community. Share your work and get feedback.

  = link_to "Let's get started!", new_post_path, class: "button get-started"