config/routes.rb
Rails.application.routes.draw do
  root "landing_pages#index"

  get "/get_synonyms/:word" => "posts#get_synonyms"

  namespace :admin do
    resources :prompts
  end

  resources :users, path: "writers"
  get "/welcome" => "users#welcome"
  get "/profile" => "users#show"
  get "/writers/:id/stats" => "users#stats", as: :stats

  resources :posts, except: [:edit]
  get "/write" => "posts#edit", as: :write
  post "/publish/:post_id" => "posts#publish", as: :publish
  post "/unpublish/:post_id" => "posts#unpublish", as: :unpublish
  get "/refresh_random_prompt" => "posts#refresh_random_prompt"

  resources :comments, only: [:create]

  resources :archive, only: [:index]
  get "/download" => "archive#download", as: :download

  resources :landing_pages

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  post "/logout" => "sessions#destroy", as: :logout

  resources :password_resets
  resources :subscriptions
  delete "/destroy_subscription" => "subscriptions#destroy",
    as: :destroy_subscription
  resources :refunds, only: [:create]
end

app/views/pages/archive.html.haml
.top-left
  = link_to "Write", root_path, class: "write-button"
  = link_to "Profile", profile_path, class: "archive-profile-link"

.top-right
  = link_to "Log out", logout_path, class: "logout", method: :post


%h1.col-sm-6.col-sm-offset-3.title
  Archive

%section.articles.col-sm-6.col-sm-offset-3
  - @posts.each do |post|
    %article
      .date
        = post.date
        %br
        = link_to "Download", download_path(id: post.id)
      = simple_format(post.content)

app/views/pages/profile.html.haml
.top-left
  = link_to "Write", root_path, class: "write-button"
  = link_to "Archive", archive_path, class: "archive-profile-link"

.top-right
  = link_to "Log out", logout_path, class: "logout", method: :post

%h1.col-sm-6.col-sm-offset-3.title
  Profile

%section.stats.col-sm-6.col-sm-offset-3
  .word-stats
    = current_user.username
    , you have written
    %span.count= @post_today ? pluralize(@post_today.word_count, "word") : pluralize(0, "word")
    today.
  .point-stats
    You have
    %span.points= pluralize(@points, "point")
  .streak-stats
    Your current streak is
    %span.days= pluralize(@current_streak, "day")

app/views/pages/writing.html.haml
- if @post_today.present?
  .word-count
    0
    %span.wordz.hidden
      words

  .saved
    Saved
    = @post_today.updated_at.strftime("%l:%M:%S%P")
   
  .close
    = link_to "X", profile_path
 
  .save-exit.hidden Save and exit 

  %article.writing-area
    %textarea.col-sm-6{autofocus: "autofocus", spellcheck: "false"}
      = @post_today.content
- else
  .top-left
    = link_to "Profile", profile_path, class: "write-button"
    = link_to "Archive", archive_path, class: "archive-profile-link"

  .top-right
    = link_to "Log out", logout_path, class: "logout", method: :post

  = link_to "Start today's writing", posts_path, class: "start-writing col-lg-6 col-lg-offset-3", method: :post