config/routes.rb
Rails.application.routes.draw do
  root "landing_pages#index"

  get "/get_synonyms/:word" => "posts#get_synonyms"

  namespace :admin do
    resources :prompts
  end

  resources :users, path: "writers"
  get "/welcome" => "users#welcome"
  get "/profile" => "users#show"
  get "/writers/:id/stats" => "users#stats", as: :stats

  resources :posts, except: [:edit]
  get "/write" => "posts#edit", as: :write
  post "/publish/:post_id" => "posts#publish", as: :publish
  post "/unpublish/:post_id" => "posts#unpublish", as: :unpublish
  get "/refresh_random_prompt" => "posts#refresh_random_prompt"

  resources :comments, only: [:create]

  resources :archive, only: [:index]
  get "/download" => "archive#download", as: :download

  resources :landing_pages

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  post "/logout" => "sessions#destroy", as: :logout

  resources :password_resets
  resources :subscriptions
  delete "/destroy_subscription" => "subscriptions#destroy",
    as: :destroy_subscription
  resources :refunds, only: [:create]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include DateFormat

  before_save :prevent_blank_content

  after_save :calculate_word_count

  belongs_to :user
  belongs_to :prompt

  has_many :comments

  include PgSearch
  pg_search_scope :search_by_content, against: :content

  scope :published,     -> { where(published: true) }
  scope :latest_post,   -> { order("created_at desc").first || NullPost.new }
  scope :on_date, -> (day) { where("created_at >= ? AND created_at <= ?",
                             day.beginning_of_day,
                             day.end_of_day) }

  def publish
    update(published: true)
  end

  def unpublish
    update(published: false)
  end

  private

  def prevent_blank_content
    return /^\s*$/ =~ content ? nil : true
  end

  def calculate_word_count
    update_column(:word_count, (content || "").split(" ").count)
  end
end

app/controllers/posts_controller.rb
class PostsController < AuthenticatedController
  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    @profile = Profile.new(@post.user, view_context)
    redirect_to user_path(current_user) unless @post.user == current_user || @post.published?
  end

  def new
    redirect_to write_path if current_user.posts.today

    @post = Post.new
    @profile = Profile.new(current_user, view_context)
    @prompt = Prompt.today
    @random_prompt = Prompt.random
  end

  def edit
    @post = current_user.posts.today || NullPost.new
    @prompt = @post.prompt || NullPrompt.new
  end

  def create
    if params[:prompt].nil?
      prompt_id = nil
    else
      prompt_id = params[:prompt]
    end

    @post = Post.create!(user_id: current_user.id,
                 content: nil,
                 word_count: 0,
                 prompt_id: prompt_id)
    current_user.update_longest_streak

    redirect_to write_path
  end

  def update
    @post = current_user.posts.today

    @post.content = post_params[:content]

    if @post.content.present? && @post.save
      @achievements = AchievementAwarder.check_achievements_for(current_user)
      flash[:achievement] = @achievements.map(&:name).zip(@achievements.map(&:tier)) unless @achievements.blank?
      respond_to do |format|
        format.js { render :action => 'update_success' }
        format.html { redirect_to profile_path }
      end
    else
      respond_to do |format|
        format.js { render :action => 'update_failure' }
        format.html {
          @post.delete
          flash[:error] = "Your blank post was not saved. Remember: blank posts don't count!" 
          redirect_to profile_path
        }
      end
    end
  end

  def publish
    post = current_user.posts.find(params[:post_id])
    post.publish

    redirect_to user_path(post.user)
  end

  def unpublish
    post = current_user.posts.find(params[:post_id])
    post.unpublish

    redirect_to user_path(post.user)
  end

  def get_synonyms
    @response = GetSynonyms.call(params[:word]).body["synonyms"]

    respond_to do |format|
      format.js
    end
  end

  def refresh_random_prompt
    @random_prompt = Prompt.random

    respond_to do |format|
      format.json { render json: json_for(@random_prompt) }
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/views/posts/_post.html.haml
.post-teaser
  .date
    = post.date
  .post-excerpt
    = link_to truncate(post.content, length: 50), post_path(post),
      class: "post-excerpt-link"
    - if @profile.current_users_profile?
      - if post.published
        = link_to "Unpublish", unpublish_path(post.id), method: :post, class: "button-light pull-right"
      - else
        = link_to "Publish", publish_path(post.id), method: :post, data: {confirm: "Publishing post. You can always unpublish."}, class: "button-light pull-right"

app/views/posts/_post_blank_state.html.haml
%h1.blank-state-explanation
  This writer has no public posts.
.filter
  .post-teaser
    .date
      11 May 2015
    .post-excerpt
      Lorem ipsum dolor sit amet...
      = link_to "Publish", "#", class: "button-light pull-right"
  .post-teaser
    .date
      11 May 2015
    .post-excerpt
      Lorem ipsum dolor sit amet...
      = link_to "Publish", "#", class: "button-light pull-right"
  .post-teaser
    .date
      11 May 2015
    .post-excerpt
      Lorem ipsum dolor sit amet...
      = link_to "Publish", "#", class: "button-light pull-right"
  .post-teaser
    .date
      11 May 2015
    .post-excerpt
      Lorem ipsum dolor sit amet...
      = link_to "Publish", "#", class: "button-light pull-right"
  .post-teaser
    .date
      11 May 2015
    .post-excerpt
      Lorem ipsum dolor sit amet...
      = link_to "Publish", "#", class: "button-light pull-right"
  .post-teaser
    .date
      11 May 2015
    .post-excerpt
      Lorem ipsum dolor sit amet...
      = link_to "Publish", "#", class: "button-light pull-right"
  .post-teaser
    .date
      11 May 2015
    .post-excerpt
      Lorem ipsum dolor sit amet...
      = link_to "Publish", "#", class: "button-light pull-right"

app/views/posts/_synonym_modal.html.haml
.overlay.overlay-synonyms
.modal.modal-synonyms
  %span.modal-top-bar
  .close.close-synonyms
    x
  %h4 Synonyms:
  %ul.synonyms-list
    - if response.present?
      - response.each do |synonym|
        %li.synonym
          = synonym
    - else
      %li.synonym
        No synonyms found.
  .scroll-indicator.hidden
    &darr;

app/views/posts/edit.html.haml
.overlay.hidden
.modal.hidden
  .close x
  %h4 Prompt:
  %p= @prompt.content
.word-count.js-willFade
  0
  %span
    words
  %br
  = link_to "Writing prompt", "#", class: "js-prompt-modal button--small", remote: true

= form_for @post, url: post_path(@post),
  data: { id: @post.id }, method: :patch do |f|
  .close.exit.js-willFade
    = f.submit "X"

  .save-exit.hidden Save and exit

  = link_to "Save", "#", class: "save-button button-light js-willFade"

  %article.writing-area
    = f.text_area :content, class: "col-sm-6",
      id: "writing-textarea", autofocus: "autofocus", spellcheck: "false"

app/views/posts/get_synonyms.js.erb
$(".container").prepend("<%= j render partial: 'synonym_modal', locals: {response: @response}%>")

app/views/posts/new.html.haml
%section.select-prompt-section.flex-center--row.flex-justify--center
  %section.select-prompt-section__today.text-center
    %h2 Today's prompt:
    %p.writing-prompt
      = @prompt.content
    = link_to "Use today's prompt", posts_path(prompt: @prompt.id), class: "start-writing",
      method: :post
  .select-prompt-section__divider
  = react_component("RandomPromptSection", path: posts_path(prompt: @random_prompt.id), prompt: @random_prompt.content )

.prompt-links.flex-center--column.flex-justify--space-between.breathe
  = link_to "Don't use prompt", posts_path(prompt: nil),
    class: "link",
    method: :post
  = link_to "Profile", profile_path, class: "button-light"

app/views/posts/show.html.haml
= render 'layouts/side_bar'

.col-sm-3.col-sm-offset-3
  = link_to "&#10094; back to my profile".html_safe, profile_path, class: "back"

.col-sm-6.post
  .date
    = @post.date
  - if @profile.current_users_profile?
    - if @post.published
      = link_to "Unpublish", unpublish_path(@post.id), method: :post, class: "button-light pull-right"
    - else
      = link_to "Publish", publish_path(@post.id), method: :post, data: {confirm: "Publishing post. You can always unpublish."}, class: "button-light pull-right"

  - if @post.prompt
    %h2.prompt
      %span Prompt:
      = @post.prompt.content
  .content
    = markdown_format @post

  .comment-box
    = react_component("CommentBox", { data: json_for(@post.comments.order(created_at: :desc)), post_id: @post.id, username: current_user.username })

app/views/posts/update.js.erb
$(".save-button").text("Saved!").addClass("confirmed-save")

setTimeout(function() {
  $(".save-button").text("Save").removeClass("confirmed-save")
}, 3000)

app/views/posts/update_failure.js.erb
$(".save-button").text("Not Saved!").addClass("failed-save")

setTimeout(function() {
  $(".save-button").text("Save").removeClass("failed-save")
}, 3000)

app/views/posts/update_success.js.erb
$(".save-button").text("Saved!").addClass("confirmed-save")

setTimeout(function() {
  $(".save-button").text("Save").removeClass("confirmed-save")
}, 3000)