config/routes.rb
Rails.application.routes.draw do
  root "landing_pages#index"

  get "/get_synonyms/:word" => "posts#get_synonyms"

  namespace :admin do
    resources :prompts
  end

  resources :users, path: "writers"
  get "/welcome" => "users#welcome"
  get "/profile" => "users#show"
  get "/writers/:id/stats" => "users#stats", as: :stats

  resources :posts, except: [:edit]
  get "/write" => "posts#edit", as: :write
  post "/publish/:post_id" => "posts#publish", as: :publish
  post "/unpublish/:post_id" => "posts#unpublish", as: :unpublish
  get "/refresh_random_prompt" => "posts#refresh_random_prompt"

  resources :comments, only: [:create]

  resources :archive, only: [:index]
  get "/download" => "archive#download", as: :download

  resources :landing_pages

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  post "/logout" => "sessions#destroy", as: :logout

  resources :password_resets
  resources :subscriptions
  delete "/destroy_subscription" => "subscriptions#destroy",
    as: :destroy_subscription
  resources :refunds, only: [:create]
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
    @posts = if params[:search]
               PostSearch.search(params[:search], current_user)
                         .paginate(page: params[:page], per_page: 10)
             else
               Post.where(user: current_user)
                    .paginate(page: params[:page], per_page: 10)
                    .order('created_at DESC')
             end
  end

  def download
    post = current_user.posts.find(params[:id])
    content = post.content
    send_data content, filename: "Writing from #{post.date}"
  end
end

app/helpers/archive_helper.rb
module ArchiveHelper
  def markdown_format(post)
    simple_format(RDiscount.new(post.content || '').to_html)
  end
end

app/views/archive/index.html.haml
.top-left
  = link_to "Write", root_path, class: "write-button"
  = link_to "Profile", profile_path, class: "archive-profile-link"

.top-right
  = link_to "Log out", logout_path, class: "logout", method: :post


%h1.col-sm-6.col-sm-offset-3.title
  Archive

%section.col-sm-6.col-sm-offset-3.search
  = form_tag archive_index_path, method: "GET" do
    = text_field_tag :search
    = submit_tag "Search"

%section.articles.col-sm-6.col-sm-offset-3
  - @posts.each do |post|
    %article
      .date
        = post.date
        %br
      = markdown_format(post)
      = link_to "Download", download_path(id: post.id), class: "link__small"
      - if post.published
        = link_to "Unpublish", unpublish_path(post.id), method: :post, class: "link__small pull-right"
      - else
        = link_to "Publish", publish_path(post.id), method: :post, class: "link__small pull-right"
      %hr

  = will_paginate @posts